In [1]:
import pandas as pd
import numpy as np

In [12]:
lines =pd.read_csv('lines.csv', sep=',', thousands=',',encoding='unicode_escape')

In [13]:
lines

,team1,team2,favorite,spread,over_under,team1_score,team2_score,team1p1,p1min,p1pts,...,p14to.1,p14oreb.1,p14dreb.1,p14fg.1,p14fg%.1,p14ft.1,p14ft%.1,p143pt.1,p143pt%.1,p14+/-.1
0,SAC,POR,POR,-4.5,237.0,97,92,Richaun Holmes (F),22,8,...,0,0,0,0/0,-,0/0,-,0/0,-,0
1,MIA,NO,MIA,-2.5,227.0,103,93,KZ Okpala (F-G),17,5,...,0,0,0,0/0,-,0/0,-,0/0,-,0
2,OKC,SA,SAS,-7.0,220.0,107,102,Isaiah Roby (F),28,12,...,0,0,0,0/0,-,0/0,-,0/0,-,0
3,MIL,MEM,MIL,-5.5,235.0,112,111,Brook Lopez (C),27,12,...,0,0,0,0/0,-,0/0,-,0/0,-,0
4,DEN,IND,DEN,-4.0,226.5,113,103,Nikola Jokic (C),37,20,...,0,0,0,0/0,-,0/0,-,0/0,-,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,ATL,CHI,ATL,-2.0,233.0,124,104,D. Gallinari (F),24,13,...,0,0,0,0/0,-,0/0,-,0/0,-,0
482,NO,TOR,TOR,-3.5,228.5,113,99,Zion Williamson (F),29,15,...,0,0,0,0/0,-,0/0,-,0/0,-,0
483,NY,IND,IND,-7.5,215.0,107,121,Julius Randle (F),35,17,...,0,0,0,0/0,-,0/0,-,0/0,-,0
484,WSH,PHI,PHI,-7.0,230.5,107,113,Deni Avdija (F),28,7,...,0,0,0,0/0,-,0/0,-,0/0,-,0
485,CHA,CLE,CHA,-2.5,216.5,114,121,P.J. Washington (F),21,4,...,0,0,0,0/0,-,0/0,-,0/0,-,0

In [14]:
lines['point_total'] = lines['team1_score'] + lines['team2_score']

In [15]:
lines['result'] = 'o'
for i in range(0, len(lines['result'])):
    if lines['point_total'][i] < lines['over_under'][i]:
         lines['result'][i] = 'u'
lines

<ipython-input-15-963f9a0e7119>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lines['result'][i] = 'u'

,team1,team2,favorite,spread,over_under,team1_score,team2_score,team1p1,p1min,p1pts,...,p14dreb.1,p14fg.1,p14fg%.1,p14ft.1,p14ft%.1,p143pt.1,p143pt%.1,p14+/-.1,point_total,result
0,SAC,POR,POR,-4.5,237.0,97,92,Richaun Holmes (F),22,8,...,0,0/0,-,0/0,-,0/0,-,0,189,u
1,MIA,NO,MIA,-2.5,227.0,103,93,KZ Okpala (F-G),17,5,...,0,0/0,-,0/0,-,0/0,-,0,196,u
2,OKC,SA,SAS,-7.0,220.0,107,102,Isaiah Roby (F),28,12,...,0,0/0,-,0/0,-,0/0,-,0,209,u
3,MIL,MEM,MIL,-5.5,235.0,112,111,Brook Lopez (C),27,12,...,0,0/0,-,0/0,-,0/0,-,0,223,u
4,DEN,IND,DEN,-4.0,226.5,113,103,Nikola Jokic (C),37,20,...,0,0/0,-,0/0,-,0/0,-,0,216,u
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,ATL,CHI,ATL,-2.0,233.0,124,104,D. Gallinari (F),24,13,...,0,0/0,-,0/0,-,0/0,-,0,228,u
482,NO,TOR,TOR,-3.5,228.5,113,99,Zion Williamson (F),29,15,...,0,0/0,-,0/0,-,0/0,-,0,212,u
483,NY,IND,IND,-7.5,215.0,107,121,Julius Randle (F),35,17,...,0,0/0,-,0/0,-,0/0,-,0,228,o
484,WSH,PHI,PHI,-7.0,230.5,107,113,Deni Avdija (F),28,7,...,0,0/0,-,0/0,-,0/0,-,0,220,u
485,CHA,CLE,CHA,-2.5,216.5,114,121,P.J. Washington (F),21,4,...,0,0/0,-,0/0,-,0/0,-,0,235,o

In [16]:
lines['point_diff'] = abs(lines['over_under'] - lines['point_total'])
for i in range(0, len(lines['point_diff'])):
    if lines['result'][i] == 'u':
        lines['point_diff'][i] *= -1
lines

<ipython-input-16-0a0517db5a3f>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lines['point_diff'][i] *= -1

,team1,team2,favorite,spread,over_under,team1_score,team2_score,team1p1,p1min,p1pts,...,p14fg.1,p14fg%.1,p14ft.1,p14ft%.1,p143pt.1,p143pt%.1,p14+/-.1,point_total,result,point_diff
0,SAC,POR,POR,-4.5,237.0,97,92,Richaun Holmes (F),22,8,...,0/0,-,0/0,-,0/0,-,0,189,u,-48.0
1,MIA,NO,MIA,-2.5,227.0,103,93,KZ Okpala (F-G),17,5,...,0/0,-,0/0,-,0/0,-,0,196,u,-31.0
2,OKC,SA,SAS,-7.0,220.0,107,102,Isaiah Roby (F),28,12,...,0/0,-,0/0,-,0/0,-,0,209,u,-11.0
3,MIL,MEM,MIL,-5.5,235.0,112,111,Brook Lopez (C),27,12,...,0/0,-,0/0,-,0/0,-,0,223,u,-12.0
4,DEN,IND,DEN,-4.0,226.5,113,103,Nikola Jokic (C),37,20,...,0/0,-,0/0,-,0/0,-,0,216,u,-10.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,ATL,CHI,ATL,-2.0,233.0,124,104,D. Gallinari (F),24,13,...,0/0,-,0/0,-,0/0,-,0,228,u,-5.0
482,NO,TOR,TOR,-3.5,228.5,113,99,Zion Williamson (F),29,15,...,0/0,-,0/0,-,0/0,-,0,212,u,-16.5
483,NY,IND,IND,-7.5,215.0,107,121,Julius Randle (F),35,17,...,0/0,-,0/0,-,0/0,-,0,228,o,13.0
484,WSH,PHI,PHI,-7.0,230.5,107,113,Deni Avdija (F),28,7,...,0/0,-,0/0,-,0/0,-,0,220,u,-10.5
485,CHA,CLE,CHA,-2.5,216.5,114,121,P.J. Washington (F),21,4,...,0/0,-,0/0,-,0/0,-,0,235,o,18.5

In [26]:
for i in range(len(lines)):
    for k in range(1,3):
        for j in range(1, 15):
            label = 'team' + str(k) + 'p' + str(j)
            if lines[label][i] == "Marc Gasol (C)":
                lines[label[0:5]][i] = 'LAL'
    if lines['team1'][i] == 'LA':
        lines['team1'][i] = 'LAC'
    elif lines['team2'][i] == 'LA':
        lines['team2'][i] = 'LAC'
lines.iloc[::-1]['team2'].unique()
lines['winner'] = ''
for i in range(len(lines['winner'])):
    if lines['team1_score'][i] > lines['team2_score'][i]:
        lines['winner'][i] = lines['team1'][i]
    else:
        lines['winner'][i] = lines['team2'][i]
    if lines['spread'][i] == 'pk':
        lines = lines.drop([i])
        lines.reset_index(drop=True, inplace=True)
        print(lines.iloc[i])

<ipython-input-26-ad9b4e028b3e>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lines[label[0:5]][i] = 'LAL'
<ipython-input-26-ad9b4e028b3e>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lines['winner'][i] = lines['team1'][i]
<ipython-input-26-ad9b4e028b3e>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lines['winner'][i] = lines['team2'][i]

In [58]:
lines.iloc[0]

team1           SAC
team2           POR
favorite        POR
spread         -4.5
over_under      237
               ...
point_total     189
result            u
point_diff      -48
winner          SAC
valid          True
Name: 0, Length: 516, dtype: object

In [46]:
lines['spread'] = lines['spread'].astype('float64')
for i in range(1,15):
    col = 'p' + str(i) + 'ft'
    col2 = col+'.1'
    col3 = 'p' + str(i) + 'fg'
    col4 = col3+'.1'
    col5 = 'p' + str(i) + '3pt'
    col6 = col5+'.1'
    col7 = 'p' + str(i) + '+/-'
    col8 = col5+'.1'
    for j in range(len(lines[col])):
        lines[col][j] = lines[col][j].split('/')[0]
        lines[col2][j] = lines[col2][j].split('/')[0]
        lines[col3][j] = lines[col3][j].split('/')[0]
        lines[col4][j] = lines[col4][j].split('/')[0]
        lines[col5][j] = lines[col3][j].split('/')[0]
        lines[col6][j] = lines[col4][j].split('/')[0]
    lines[col] = lines[col].astype('float64')
    lines[col2] = lines[col2].astype('float64')
    lines[col3] = lines[col3].astype('float64')
    lines[col4] = lines[col4].astype('float64')
    lines[col5] = lines[col5].astype('float64')
    lines[col6] = lines[col6].astype('float64')
    lines[col7] = lines[col7].astype('float64')
    lines[col8] = lines[col8].astype('float64')
    col = 'p' + str(i) + 'fg%'
    col2 = col+'.1'
    col3 = 'p' + str(i) + 'ft%'
    col4 = col3+'.1'
    col5 = 'p' + str(i) + '3pt%'
    col6 = col5+'.1'
    for j in range(len(lines[col])):
        if lines[col][j] == '-':
            lines[col][j] = '0'
        if lines[col2][j] == '-':
            lines[col2][j] = '0'
        if lines[col3][j] == '-':
            lines[col3][j] = '0'
        if lines[col4][j] == '-':
            lines[col4][j] = '0'
        if lines[col5][j] == '-':
            lines[col5][j] = '0'
        if lines[col6][j] == '-':
            lines[col6][j] = '0'
    lines[col] = lines[col].astype('float64')
    lines[col2] = lines[col2].astype('float64')
    lines[col3] = lines[col3].astype('float64')
    lines[col4] = lines[col4].astype('float64')
    lines[col5] = lines[col5].astype('float64')
    lines[col6] = lines[col6].astype('float64')
lines

<ipython-input-46-249128fb7c77>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lines[col][j] = lines[col][j].split('/')[0]
<ipython-input-46-249128fb7c77>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lines[col2][j] = lines[col2][j].split('/')[0]
<ipython-input-46-249128fb7c77>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lines[col3][j] = lines[col3][j].split('/')[0]
<ipython-input-46-249128fb7c77>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lines[col4][j] = lines[col4][j].split('/')[0]
<ipython-input-46-249128fb7c77>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lines[col5][j] = lines[col3][j].split('/')[0]
<ipython-input-46-249128fb7c77>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lines[col6][j] = lines[col4][j].split('/')[0]
<ipython-input-46-249128fb7c77>:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lines[col3][j] = '0'
<ipython-input-46-249128fb7c77>:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lines[col4][j] = '0'
<ipython-input-46-249128fb7c77>:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lines[col5][j] = '0'
<ipython-input-46-249128fb7c77>:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lines[col6][j] = '0'

,team1,team2,favorite,spread,over_under,team1_score,team2_score,team1p1,p1min,p1pts,...,p14fg%.1,p14ft.1,p14ft%.1,p143pt.1,p143pt%.1,p14+/-.1,point_total,result,point_diff,winner
0,SAC,POR,POR,-4.5,237.0,97,92,Richaun Holmes (F),22,8,...,0.0,0.0,0.0,0.0,0.0,0,189,u,-48.0,SAC
1,MIA,NO,MIA,-2.5,227.0,103,93,KZ Okpala (F-G),17,5,...,0.0,0.0,0.0,0.0,0.0,0,196,u,-31.0,MIA
2,OKC,SA,SAS,-7.0,220.0,107,102,Isaiah Roby (F),28,12,...,0.0,0.0,0.0,0.0,0.0,0,209,u,-11.0,OKC
3,MIL,MEM,MIL,-5.5,235.0,112,111,Brook Lopez (C),27,12,...,0.0,0.0,0.0,0.0,0.0,0,223,u,-12.0,MIL
4,DEN,IND,DEN,-4.0,226.5,113,103,Nikola Jokic (C),37,20,...,0.0,0.0,0.0,0.0,0.0,0,216,u,-10.5,DEN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477,ATL,CHI,ATL,-2.0,233.0,124,104,D. Gallinari (F),24,13,...,0.0,0.0,0.0,0.0,0.0,0,228,u,-5.0,ATL
478,NO,TOR,TOR,-3.5,228.5,113,99,Zion Williamson (F),29,15,...,0.0,0.0,0.0,0.0,0.0,0,212,u,-16.5,NO
479,NY,IND,IND,-7.5,215.0,107,121,Julius Randle (F),35,17,...,0.0,0.0,0.0,0.0,0.0,0,228,o,13.0,IND
480,WSH,PHI,PHI,-7.0,230.5,107,113,Deni Avdija (F),28,7,...,0.0,0.0,0.0,0.0,0.0,0,220,u,-10.5,PHI
481,CHA,CLE,CHA,-2.5,216.5,114,121,P.J. Washington (F),21,4,...,0.0,0.0,0.0,0.0,0.0,0,235,o,18.5,CLE

In [55]:
x = 5
data = pd.DataFrame(columns=['team1', '1recordx', '1record', '1o/u1','1o/uline1', '1o/u2','1o/uline2','1o/u3','1o/uline3','1o/u4','1o/uline4','1o/u5','1o/uline5', '1spreadx', 'spread', 'o/u', '1ptsx', '1ptslg', '1ptsvar', '1astsx','1astslg', '1rebsx', '1rebslg', '1pfsx', '1pfslg', '1tosx', '1toslg', '1fgpercx', '1fgperclg', '13percx', '13perclg', '1ftx', '1ftlg', 'team2', '2recordx', '2record', '2o/u1','2o/uline1', '2o/u2','2o/uline2','2o/u3','2o/uline3','2o/u4','2o/uline4','2o/u5','2o/uline5', '2spreadx', '2ptsx', '2ptslg', '2ptsvar', '2astsx','2astslg', '2rebsx', '2rebslg', '2pfsx', '2pfslg', '2tosx', '2toslg', '2fgpercx', '2fgperclg', '23percx', '23perclg', '2ftx', '2ftlg', 'over', 'under', 'hold'])
data

Empty DataFrame
Columns: [team1, 1recordx, 1record, 1o/u1, 1o/uline1, 1o/u2, 1o/uline2, 1o/u3, 1o/uline3, 1o/u4, 1o/uline4, 1o/u5, 1o/uline5, 1spreadx, spread, o/u, 1ptsx, 1ptslg, 1ptsvar, 1astsx, 1astslg, 1rebsx, 1rebslg, 1pfsx, 1pfslg, 1tosx, 1toslg, 1fgpercx, 1fgperclg, 13percx, 13perclg, 1ftx, 1ftlg, team2, 2recordx, 2record, 2o/u1, 2o/uline1, 2o/u2, 2o/uline2, 2o/u3, 2o/uline3, 2o/u4, 2o/uline4, 2o/u5, 2o/uline5, 2spreadx, 2ptsx, 2ptslg, 2ptsvar, 2astsx, 2astslg, 2rebsx, 2rebslg, 2pfsx, 2pfslg, 2tosx, 2toslg, 2fgpercx, 2fgperclg, 23percx, 23perclg, 2ftx, 2ftlg, over, under, hold]
Index: []

[0 rows x 67 columns]

In [56]:
tracker = {}
lines = lines.reset_index(drop=True)
lines['valid'] = False
teams = sorted(lines.iloc[::-1]['team2'].unique())
for i in teams:
    tracker[i]= 0
for i in range(len(lines['team1'])-1, -1, -1):
    if tracker[lines['team1'][i]] != x:
        tracker[lines['team1'][i]] += 1
    if tracker[lines['team2'][i]] != x:
        tracker[lines['team2'][i]] += 1
    elif tracker[lines['team2'][i]] == 5 and tracker[lines['team1'][i]] == 5:
        lines['valid'][i] = True
lines['valid'].value_counts()

<ipython-input-56-52b2ab484225>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lines['valid'][i] = True

True     405
False     77
Name: valid, dtype: int64

In [ ]:
#record , ptsvar, all lg fields
def get_xstats(index, team):
    stop = 0
    stats = [team, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] #team, recordx, over_underx, spreadx, ptsx, spread, o/u, ptslg, rebsx, astsx, stlx, blkx, pfx, tox, fgpercx, threepercx, ftx 
    stats[5] = lines['spread'][index]
    stats[6] = lines['over_under'][index]
    cols = [10,11,12,13,14,15,18, 19, 20, 21, 22, 23] #reb, ast, stl, blk, pf, to, fg, fg%, ft, ft%, 3pt, 3pt%
    jump = 18
    for j in range(index+1, len(lines['team1'])):
        if stop == 5:
            break
        if lines['team1'][j] == team or lines['team2'][j] == team:
            team1 = True if lines['team1'][j] == team else False
            stop += 1
            stats[1] = stats[1] + 1 if lines['winner'][j] == team else stats[1]
            stats[2] = lines['over_under'][j]
            stats[3] += abs(lines['spread'][j]) #divide by x 
            stats[4] += lines['team1_score'][j] if lines['team1'][j] == team else lines['team2_score'][j] #divide by x
            stats.append(0) if lines['result'][j] == 'u' else stats.append(1)
            stats.append(lines['over_under'][j])
            
            if stop == 1:
                stats[7] = lines['team1_score'][j] if team1 else lines['team2_score'][j]
            fg = 0
            ft = 0
            threes = 0
            fgtot = 0
            threestot = 0
            for i in range(14):
                features = [i*jump + col for col in cols] if team1 else [i*jump + col + 252 for col in cols]
                
                for k in range(8, 14):
                    stats[k] += lines.iloc[j,features[k-8]] #all divide by x (8-13)
                fgtot += lines.iloc[j, 6]/lines.iloc[j, 7]
                fg += lines.iloc[j, 6]
                ft += lines.iloc[j, 8]
                threestot += lines.iloc[j, 10]/lines.iloc[j, 11]
                threes += lines.iloc[j, 10]
            stats[14] += fg/fgtot #divide by x
            stats[15] += threes/threestot #divide by x
            stats[16] += ft # divide by x
            
                
for i in range(len(lines['team1'])):
    row = []
    if lines['valid'][i] == True:
        team1 = lines['team1'][i]
        team2 = lines['team2'][i]
        row.append(lines['team1'][i])