In [54]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [55]:
lines =pd.read_csv('lines.csv', sep=',', thousands=',',encoding='unicode_escape')

In [56]:
lines

,team1,team2,favorite,spread,over_under,team1_score,team2_score,team1p1,p1min,p1pts,...,p14to.1,p14oreb.1,p14dreb.1,p14fg.1,p14fg%.1,p14ft.1,p14ft%.1,p143pt.1,p143pt%.1,p14+/-.1
0,DEN,LA,LAC,-1.5,220.0,101,94,Nikola Jokic (C),35,14,...,0,0,0,0/0,-,0/0,-,0/0,-,0
1,ATL,SA,SAS,-1.0,222.5,134,129,Clint Capela (C),44,28,...,0,0,0,0/0,-,0/0,-,0/0,-,0
2,ORL,NO,NOP,-5.0,213.0,115,110,Khem Birch (C),5,0,...,0,0,0,0/0,-,0/0,-,0/0,-,0
3,GS,MIA,MIA,-3.0,218.0,109,116,James Wiseman (C),19,4,...,0,0,0,0/0,-,0/0,-,0/0,-,0
4,CHA,BKN,BKN,-3.0,222.5,89,111,Bismack Biyombo (C),10,2,...,0,0,0,0/0,-,0/0,-,0/0,-,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,NO,TOR,TOR,-3.5,228.5,113,99,Zion Williamson (F),29,15,...,0,0,0,0/0,-,0/0,-,0/0,-,0
671,NY,IND,IND,-7.5,215.0,107,121,Julius Randle (F-C),35,17,...,0,0,0,0/0,-,0/0,-,0/0,-,0
672,WSH,PHI,PHI,-7.0,230.5,107,113,Deni Avdija (F),28,7,...,0,0,0,0/0,-,0/0,-,0/0,-,0
673,CHA,CLE,CHA,-2.5,216.5,114,121,P.J. Washington (F),21,4,...,0,0,0,0/0,-,0/0,-,0/0,-,0
674,MIA,ORL,MIA,-5.0,218.0,107,113,M. Harkless (F-G),22,3,...,0,0,0,0/0,-,0/0,-,0/0,-,0

In [57]:
lines['point_total'] = lines['team1_score'] + lines['team2_score']

In [58]:
lines['result'] = 'o'
for i in range(0, len(lines['result'])):
    if lines['point_total'][i] < lines['over_under'][i]:
         lines['result'][i] = 'u'
lines

,team1,team2,favorite,spread,over_under,team1_score,team2_score,team1p1,p1min,p1pts,...,p14dreb.1,p14fg.1,p14fg%.1,p14ft.1,p14ft%.1,p143pt.1,p143pt%.1,p14+/-.1,point_total,result
0,DEN,LA,LAC,-1.5,220.0,101,94,Nikola Jokic (C),35,14,...,0,0/0,-,0/0,-,0/0,-,0,195,u
1,ATL,SA,SAS,-1.0,222.5,134,129,Clint Capela (C),44,28,...,0,0/0,-,0/0,-,0/0,-,0,263,o
2,ORL,NO,NOP,-5.0,213.0,115,110,Khem Birch (C),5,0,...,0,0/0,-,0/0,-,0/0,-,0,225,o
3,GS,MIA,MIA,-3.0,218.0,109,116,James Wiseman (C),19,4,...,0,0/0,-,0/0,-,0/0,-,0,225,o
4,CHA,BKN,BKN,-3.0,222.5,89,111,Bismack Biyombo (C),10,2,...,0,0/0,-,0/0,-,0/0,-,0,200,u
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,NO,TOR,TOR,-3.5,228.5,113,99,Zion Williamson (F),29,15,...,0,0/0,-,0/0,-,0/0,-,0,212,u
671,NY,IND,IND,-7.5,215.0,107,121,Julius Randle (F-C),35,17,...,0,0/0,-,0/0,-,0/0,-,0,228,o
672,WSH,PHI,PHI,-7.0,230.5,107,113,Deni Avdija (F),28,7,...,0,0/0,-,0/0,-,0/0,-,0,220,u
673,CHA,CLE,CHA,-2.5,216.5,114,121,P.J. Washington (F),21,4,...,0,0/0,-,0/0,-,0/0,-,0,235,o
674,MIA,ORL,MIA,-5.0,218.0,107,113,M. Harkless (F-G),22,3,...,0,0/0,-,0/0,-,0/0,-,0,220,o

In [59]:
lines['point_diff'] = abs(lines['over_under'] - lines['point_total'])
for i in range(0, len(lines['point_diff'])):
    if lines['result'][i] == 'u':
        lines['point_diff'][i] *= -1
lines['result'].value_counts()

o    340
u    335
Name: result, dtype: int64

In [60]:
for i in range(len(lines)):
    for k in range(1,3):
        for j in range(1, 15):
            label = 'team' + str(k) + 'p' + str(j)
            if lines[label][i] == "Marc Gasol (C)":
                lines[label[0:5]][i] = 'LAL'
    if lines['team1'][i] == 'LA':
        lines['team1'][i] = 'LAC'
    elif lines['team2'][i] == 'LA':
        lines['team2'][i] = 'LAC'
lines.iloc[::-1]['team2'].unique()
lines['winner'] = ''
length = len(lines['winner']) - lines['spread'].value_counts()['pk']
for i in range(length):
    if lines['team1_score'][i] > lines['team2_score'][i]:
        lines['winner'][i] = lines['team1'][i]
    else:
        lines['winner'][i] = lines['team2'][i]
    if lines['spread'][i] == 'pk':
        lines = lines.drop([i])
        lines.reset_index(drop=True, inplace=True)
        length -=1
        print(lines.iloc[i])
        if lines['team1_score'][i] > lines['team2_score'][i]:
            lines['winner'][i] = lines['team1'][i]
        else:
            lines['winner'][i] = lines['team2'][i]

team1            NY
team2            SA
favorite        NYK
spread         -2.5
over_under      212
               ...
p14+/-.1          0
point_total     212
result            o
point_diff        0
winner
Name: 204, Length: 515, dtype: object
team1            SAC
team2            MIL
favorite         MIL
spread         -10.0
over_under       240
               ...
p14+/-.1           0
point_total      243
result             o
point_diff         3
winner
Name: 269, Length: 515, dtype: object
team1            IND
team2            MIN
favorite         IND
spread          -5.0
over_under     225.5
               ...
p14+/-.1           0
point_total      262
result             o
point_diff      36.5
winner
Name: 294, Length: 515, dtype: object
team1            PHI
team2            PHX
favorite         PHX
spread          -1.0
over_under     221.5
               ...
p14+/-.1          -3
point_total      231
result             o
point_diff       9.5
winner
Name: 325, Length: 515, dtype: object

In [61]:
lines.iloc[0]

team1           DEN
team2           LAC
favorite        LAC
spread         -1.5
over_under      220
               ...
p14+/-.1          0
point_total     195
result            u
point_diff      -25
winner          DEN
Name: 0, Length: 515, dtype: object

In [62]:
lines['spread'] = lines['spread'].astype('float64')
for i in range(1,15):
    col = 'p' + str(i) + 'ft'
    col2 = col+'.1'
    col3 = 'p' + str(i) + 'fg'
    col4 = col3+'.1'
    col5 = 'p' + str(i) + '3pt'
    col6 = col5+'.1'
    col7 = 'p' + str(i) + '+/-'
    col8 = col5+'.1'
    for j in range(len(lines[col])):
        lines[col][j] = lines[col][j].split('/')[0]
        lines[col2][j] = lines[col2][j].split('/')[0]
        lines[col3][j] = lines[col3][j].split('/')[0]
        lines[col4][j] = lines[col4][j].split('/')[0]
        lines[col5][j] = lines[col3][j].split('/')[0]
        lines[col6][j] = lines[col4][j].split('/')[0]
    lines[col] = lines[col].astype('float64')
    lines[col2] = lines[col2].astype('float64')
    lines[col3] = lines[col3].astype('float64')
    lines[col4] = lines[col4].astype('float64')
    lines[col5] = lines[col5].astype('float64')
    lines[col6] = lines[col6].astype('float64')
    lines[col7] = lines[col7].astype('float64')
    lines[col8] = lines[col8].astype('float64')
    col = 'p' + str(i) + 'fg%'
    col2 = col+'.1'
    col3 = 'p' + str(i) + 'ft%'
    col4 = col3+'.1'
    col5 = 'p' + str(i) + '3pt%'
    col6 = col5+'.1'
    for j in range(len(lines[col])):
        if lines[col][j] == '-':
            lines[col][j] = '0'
        if lines[col2][j] == '-':
            lines[col2][j] = '0'
        if lines[col3][j] == '-':
            lines[col3][j] = '0'
        if lines[col4][j] == '-':
            lines[col4][j] = '0'
        if lines[col5][j] == '-':
            lines[col5][j] = '0'
        if lines[col6][j] == '-':
            lines[col6][j] = '0'
    lines[col] = lines[col].astype('float64')
    lines[col2] = lines[col2].astype('float64')
    lines[col3] = lines[col3].astype('float64')
    lines[col4] = lines[col4].astype('float64')
    lines[col5] = lines[col5].astype('float64')
    lines[col6] = lines[col6].astype('float64')
lines

,team1,team2,favorite,spread,over_under,team1_score,team2_score,team1p1,p1min,p1pts,...,p14fg%.1,p14ft.1,p14ft%.1,p143pt.1,p143pt%.1,p14+/-.1,point_total,result,point_diff,winner
0,DEN,LAC,LAC,-1.5,220.0,101,94,Nikola Jokic (C),35,14,...,0.0,0.0,0.0,0.0,0.0,0,195,u,-25.0,DEN
1,ATL,SA,SAS,-1.0,222.5,134,129,Clint Capela (C),44,28,...,0.0,0.0,0.0,0.0,0.0,0,263,o,40.5,ATL
2,ORL,NO,NOP,-5.0,213.0,115,110,Khem Birch (C),5,0,...,0.0,0.0,0.0,0.0,0.0,0,225,o,12.0,ORL
3,GS,MIA,MIA,-3.0,218.0,109,116,James Wiseman (C),19,4,...,0.0,0.0,0.0,0.0,0.0,0,225,o,7.0,MIA
4,CHA,BKN,BKN,-3.0,222.5,89,111,Bismack Biyombo (C),10,2,...,0.0,0.0,0.0,0.0,0.0,0,200,u,-22.5,BKN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
666,NO,TOR,TOR,-3.5,228.5,113,99,Zion Williamson (F),29,15,...,0.0,0.0,0.0,0.0,0.0,0,212,u,-16.5,NO
667,NY,IND,IND,-7.5,215.0,107,121,Julius Randle (F-C),35,17,...,0.0,0.0,0.0,0.0,0.0,0,228,o,13.0,IND
668,WSH,PHI,PHI,-7.0,230.5,107,113,Deni Avdija (F),28,7,...,0.0,0.0,0.0,0.0,0.0,0,220,u,-10.5,PHI
669,CHA,CLE,CHA,-2.5,216.5,114,121,P.J. Washington (F),21,4,...,0.0,0.0,0.0,0.0,0.0,0,235,o,18.5,CLE
670,MIA,ORL,MIA,-5.0,218.0,107,113,M. Harkless (F-G),22,3,...,0.0,0.0,0.0,0.0,0.0,0,220,o,2.0,ORL

In [63]:
for i in range(len(lines['winner'])):
    if lines['favorite'][i] == 'SAS':
        lines['favorite'][i] = 'SA'
    elif lines['favorite'][i] == 'NOP':
        lines['favorite'][i] = 'NO'
    elif lines['favorite'][i] == 'NYK':
        lines['favorite'][i] = 'NY'
teams = list(set(lines['team2']))
hasher = {}
for i in range(len(lines['winner'])):
    if lines['team1'][i] not in hasher.keys():
        hasher[lines['team1'][i]] = [1,0,0,0]
    if lines['team2'][i] not in hasher.keys():
        hasher[lines['team2'][i]] = [1,0,0,0]
    else:
        hasher[lines['winner'][i]] = [1,0,0,0]
    if lines['winner'][i] in hasher.keys():
        hasher[lines['winner'][i]][0] += 1
    else:
        hasher[lines['winner'][i]] = [1,0,0,0]
    hasher[lines['team1'][i]][1] += lines['team1_score'][i]
    hasher[lines['team2'][i]][1] += lines['team2_score'][i]
    hasher[lines['team1'][i]][3] += 1
    hasher[lines['team2'][i]][3] += 1
for i in range(len(lines['winner'])):
    hasher[lines['team1'][i]][2] += abs(lines['team1_score'][i] - hasher[lines['team1'][i]][1]/hasher[lines['team1'][i]][3])**2
    hasher[lines['team2'][i]][2] += abs(lines['team2_score'][i] - hasher[lines['team2'][i]][1]/hasher[lines['team2'][i]][3])**2
for i in hasher.keys():
    hasher[i][2] /= hasher[i][3]-1
hasher

{'DEN': [2, 246, 6726.0, 2],
 'LAC': [2, 197, 19630.25, 2],
 'ATL': [2, 124, inf, 1],
 'SA': [2, 131, inf, 1],
 'ORL': [2, 113, inf, 1],
 'NO': [2, 113, inf, 1],
 'GS': [2, 129, inf, 1],
 'MIA': [2, 323, 3948.111111111112, 3],
 'CHA': [2, 327, 2316.5, 3],
 'BKN': [2, 360, 3948.0, 3],
 'WSH': [2, 577, 2019.3400000000006, 5],
 'DET': [2, 542, 1364.6799999999998, 5],
 'PHI': [2, 113, inf, 1],
 'CLE': [2, 121, inf, 1],
 'CHI': [2, 347, 3243.833333333334, 3],
 'PHX': [2, 219, 4413.25, 2],
 'MIL': [2, 254, 9898.0, 2],
 'LAL': [2, 127, inf, 1],
 'SAC': [2, 124, inf, 1],
 'UTA': [2, 120, inf, 1],
 'MEM': [2, 347, 3471.611111111112, 3],
 'NY': [2, 326, 3437.333333333335, 3],
 'MIN': [2, 111, inf, 1],
 'TOR': [2, 681, 1199.35, 6],
 'OKC': [2, 109, inf, 1],
 'DAL': [2, 124, inf, 1],
 'BOS': [2, 233, 7134.75, 2],
 'HOU': [2, 339, 3928.5, 3],
 'IND': [2, 121, inf, 1],
 'POR': [2, 228, 6123.0, 2]}

In [64]:
x = 5
data = pd.DataFrame(columns=['team1', '1recordx', '1record', '1o/u1','1o/uline1', '1o/u2','1o/uline2','1o/u3','1o/uline3','1o/u4','1o/uline4','1o/u5','1o/uline5', '1spreadx', 'spread', 'o/u', '1ptsx', '1ptslg', '1ptsvar', '1astsx','1astslg', '1rebsx', '1rebslg', '1pfsx', '1pfslg', '1tosx', '1toslg', '1fgpercx', '1fgperclg', '13percx', '13perclg', '1ftx', '1ftlg', 'team2', '2recordx', '2record', '2o/u1','2o/uline1', '2o/u2','2o/uline2','2o/u3','2o/uline3','2o/u4','2o/uline4','2o/u5','2o/uline5', '2spreadx', '2ptsx', '2ptslg', '2ptsvar', '2astsx','2astslg', '2rebsx', '2rebslg', '2pfsx', '2pfslg', '2tosx', '2toslg', '2fgpercx', '2fgperclg', '23percx', '23perclg', '2ftx', '2ftlg', 'over', 'under', 'hold'])
data

Empty DataFrame
Columns: [team1, 1recordx, 1record, 1o/u1, 1o/uline1, 1o/u2, 1o/uline2, 1o/u3, 1o/uline3, 1o/u4, 1o/uline4, 1o/u5, 1o/uline5, 1spreadx, spread, o/u, 1ptsx, 1ptslg, 1ptsvar, 1astsx, 1astslg, 1rebsx, 1rebslg, 1pfsx, 1pfslg, 1tosx, 1toslg, 1fgpercx, 1fgperclg, 13percx, 13perclg, 1ftx, 1ftlg, team2, 2recordx, 2record, 2o/u1, 2o/uline1, 2o/u2, 2o/uline2, 2o/u3, 2o/uline3, 2o/u4, 2o/uline4, 2o/u5, 2o/uline5, 2spreadx, 2ptsx, 2ptslg, 2ptsvar, 2astsx, 2astslg, 2rebsx, 2rebslg, 2pfsx, 2pfslg, 2tosx, 2toslg, 2fgpercx, 2fgperclg, 23percx, 23perclg, 2ftx, 2ftlg, over, under, hold]
Index: []

[0 rows x 67 columns]

In [65]:
tracker = {}
lines = lines.reset_index(drop=True)
lines['valid'] = False
teams = sorted(lines.iloc[::-1]['team2'].unique())
for i in teams:
    tracker[i]= 0
for i in range(len(lines['team1'])-1, -1, -1):
    if tracker[lines['team1'][i]] != x:
        tracker[lines['team1'][i]] += 1
    if tracker[lines['team2'][i]] != x:
        tracker[lines['team2'][i]] += 1
    elif tracker[lines['team2'][i]] == 5 and tracker[lines['team1'][i]] == 5:
        lines['valid'][i] = True
lines['valid'].value_counts()

True     595
False     76
Name: valid, dtype: int64

In [66]:
#ptsvar
def get_xstats(index, team):
    stop = 0                                                                      #0        1           2        3          4    5      6   7        8    9     10   11    12        13         14    15      16      17     18     19         20     21
    stats = [team, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] #team, recordx, over_underx, spreadx, ptsx, spread, o/u, ptslg, rebsx, astsx, pfx, tox, fgpercx, threepercx, ftx, rebslg, astslg, pfslg, toslg, fgperclg, 3perclg, ftlg 
    stats[5] = lines['spread'][index]
    stats[6] = lines['over_under'][index]
    cols = [10,11,14,15,18, 19, 20, 21, 22, 23] #reb, ast, pf, to, fg, fg%, ft, ft%, 3pt, 3pt%
    jump = 18
    for j in range(index+1, len(lines['team1'])):
        if stop == 5:
            break
        if lines['team1'][j] == team or lines['team2'][j] == team:
            team1 = True if lines['team1'][j] == team else False
            stop += 1
            stats[1] = stats[1] + 1 if lines['winner'][j] == team else stats[1]
            stats[2] = lines['over_under'][j]
            stats[3] += abs(lines['spread'][j]) #divide by x 
            stats[4] += lines['team1_score'][j] if lines['team1'][j] == team else lines['team2_score'][j] #divide by x
            stats.append(0) if lines['result'][j] == 'u' else stats.append(1)
            stats.append(lines['over_under'][j])
            
            fg = 0
            ft = 0
            threes = 0
            fgtot = 0
            threestot = 0
            if stop == 1:
                stats[7] = lines['team1_score'][j] if team1 else lines['team2_score'][j]
                for i in range(14):
                    features = [i*jump + col for col in cols] if team1 else [i*jump + col + 252 for col in cols]
                
                    for k in range(15, 19):
                        stats[k] += lines.iloc[j,features[k-15]] 
                    fgtot += round(lines.iloc[j, features[4]]/lines.iloc[j, features[5]]) if lines.iloc[j, features[5]] != 0 else 0
                    fg += lines.iloc[j, features[4]]
                    ft += lines.iloc[j, features[6]]
                    threestot += round(lines.iloc[j, features[8]]/lines.iloc[j, features[9]]) if lines.iloc[j, features[9]] != 0 else 0
                    threes += lines.iloc[j, features[8]]
                stats[12] += fg/fgtot #divide by x
                stats[13] += threes/threestot #divide by x
                stats[14] += ft # divide by x
                stats[19] = fg/fgtot 
                stats[20] = threes/threestot 
                stats[21] = ft
            else:
                for i in range(14):
                    features = [i*jump + col for col in cols] if team1 else [i*jump + col + 252 for col in cols]

                    for k in range(8, 12):
                        stats[k] += lines.iloc[j,features[k-8]] #all divide by x (8-13)
                    fgtot += round(lines.iloc[j, features[4]]/lines.iloc[j, features[5]]) if lines.iloc[j, features[5]] != 0 else 0
                    fg += lines.iloc[j, features[4]]
                    ft += lines.iloc[j, features[6]]

                    threestot += round(lines.iloc[j, features[8]]/lines.iloc[j, features[9]]) if lines.iloc[j, features[9]] != 0 else 0
                    threes += lines.iloc[j, features[8]]
                stats[12] += fg/fgtot #divide by x
                stats[13] += threes/threestot #divide by x
                stats[14] += ft # divide by x
    for k in range(8, 12):
        stats[k] /= x
    for k in range(15, 19):
        stats[k] /= x
    stats[3] /= x
    stats[4] /= x
    stats[12] /= x
    stats[13] /= x
    stats[14] /= x    
    return stats

def get_rest(index):
    ptsvar1, ptsvar2 = 0, 0
    team1, team2 = lines['team1'][index], lines['team2'][index]
    mean1, mean2 = [], []
    for i in range(len(lines['team1'])):
        if lines['team1'][i] == team1:
            mean1.append(lines['team1_score'][i])
        if lines['team2'][i] == team1:
            mean1.append(lines['team2_score'][i])
        if lines['team1'][i] == team2:
            mean2.append(lines['team1_score'][i])
        if lines['team2'][i] == team2:
            mean2.append(lines['team2_score'][i])
    ptsmean1 = sum(mean1)/len(mean1)
    ptsmean2 = sum(mean2)/len(mean2)
    for i in mean1:
        ptsvar1 += (i - ptsmean1)**2
    for j in mean2:
        ptsvar2 += (j - ptsmean2)**2
    return ptsvar1/(len(mean1)-1), ptsvar2/(len(mean2)-1)
    
    
get_xstats(0, 'LAL')
for ind in range(len(lines['team1'])):
    row = []
    if lines['valid'][ind] == True:
        team1 = lines['team1'][ind]
        team2 = lines['team2'][ind]
        data1 = get_xstats(i, team1)
        data2 = get_xstats(i, team2)
        var1, var2 = get_rest(ind)
        order = [0,1,'rec',-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,3,5,6,4,7,'var',9,16,8,15,10,17,11,18,12,19,13,20,14,21]
        for i in order:
            if i == 'rec':
                row.append(lines['winner'].value_counts()[team1])
            elif i == 'var':
                row.append(var1)
            else:
                row.append(data1[i])
        order = order[0:14] + order[16:]
        for i in order:
            if i == 'rec':
                row.append(lines['winner'].value_counts()[team2])
            elif i == 'var':
                row.append(var2)
            else:
                row.append(data2[i])

        if  lines['over_under'][ind] - lines['point_total'][ind] >= 8:
            row.append(0)
            row.append(1)
            row.append(0)
        elif lines['point_total'][ind] - lines['over_under'][ind] >= 8:
            row.append(1)
            row.append(0)
            row.append(0)
        else:
            row.append(0)
            row.append(0)
            row.append(1)
        data = data.append(dict(zip(data.columns, row)), ignore_index=True)
data

,team1,1recordx,1record,1o/u1,1o/uline1,1o/u2,1o/uline2,1o/u3,1o/uline3,1o/u4,...,2toslg,2fgpercx,2fgperclg,23percx,23perclg,2ftx,2ftlg,over,under,hold
0,DEN,4,30,0,220.5,1,221.0,0,230.5,1,...,2.8,0.490498,0.415730,0.645860,0.474359,15.0,10.0,0,1,0
1,ATL,2,24,1,221.0,1,218.0,0,230.5,1,...,2.2,0.481880,0.522222,0.791178,0.671429,14.0,11.0,1,0,0
2,ORL,1,17,0,208.5,1,216.5,1,215.0,0,...,2.8,0.520521,0.506173,0.850896,0.773585,20.2,17.0,1,0,0
3,GS,1,20,1,218.0,1,228.5,0,218.5,0,...,2.4,0.466442,0.430233,0.701567,0.948718,14.0,14.0,0,0,1
4,CHA,3,23,0,220.0,1,213.5,0,223.0,0,...,2.8,0.456676,0.481928,0.553357,0.493827,19.2,22.0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590,CLE,1,17,0,221.0,0,225.5,0,207.5,0,...,2.0,0.433685,0.414634,0.499805,0.382022,13.8,14.0,0,1,0
591,CHA,3,23,0,220.0,1,213.5,0,223.0,0,...,3.2,0.517946,0.541667,0.721363,0.672414,19.4,24.0,0,0,1
592,LAC,4,28,1,230.0,1,220.0,0,220.5,1,...,2.8,0.471353,0.419753,0.473241,0.404762,16.0,25.0,0,0,1
593,UTA,5,34,0,221.0,1,227.0,1,228.0,0,...,2.2,0.481880,0.522222,0.791178,0.671429,14.0,11.0,1,0,0
594,LAL,4,27,0,208.5,0,207.5,0,214.0,0,...,3.2,0.489485,0.541176,0.568433,0.657143,14.8,17.0,0,1,0

In [67]:
data.to_csv('data.csv', index = False)